services:
  db_test:
    image: postgres:14
    container_name: postgres_test_db
    env_file: 
      - .env.test
    ports:
      - "5433:5432"  # bind container's 5432 to host's 5433 to avoid conflicts
    volumes:
      - db_test_data:/var/lib/postgresql/data

  web_test:
    build: .
    container_name: flask_test_app
    env_file: 
      - .env.test
    environment:
      POSTGRES_HOST: db_test
    depends_on:
      - db_test
    command: pytest --disable-warnings -s  # automatically run tests

volumes:
  db_test_data:
