services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    restart: always
    env_file: 
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      bash -c "
      alembic upgrade head &&
      python -m app.main
      "

volumes:
  db_data:
